apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: portfolio-app
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      email VARCHAR(255) UNIQUE NOT NULL,
      password VARCHAR(255) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS portfolios (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id),
      name VARCHAR(255) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS holdings (
      id SERIAL PRIMARY KEY,
      portfolio_id INTEGER REFERENCES portfolios(id),
      symbol VARCHAR(10) NOT NULL,
      shares DECIMAL NOT NULL,
      purchase_price DECIMAL NOT NULL,
      purchase_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
