apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
  namespace: portfolio-app
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        # Portfolio service proxy
        location /api/ {
            proxy_pass http://portfolio-service:3000/api/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Auth service proxy
        location /auth/ {
            proxy_pass http://auth-service:4000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            
            # CORS headers
            add_header "Access-Control-Allow-Origin" "*" always;
            add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS, PUT, DELETE" always;
            add_header "Access-Control-Allow-Headers" "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization" always;
            add_header "Access-Control-Expose-Headers" "Content-Length,Content-Range" always;
            
            if ($request_method = "OPTIONS") {
                add_header "Access-Control-Allow-Origin" "*";
                add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS, PUT, DELETE";
                add_header "Access-Control-Allow-Headers" "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization";
                add_header "Access-Control-Max-Age" 1728000;
                add_header "Content-Type" "text/plain; charset=utf-8";
                add_header "Content-Length" 0;
                return 204;
            }
        }

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
    }