apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: portfolio-service
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: portfolio-app
spec:
  namespaceSelector:
    matchNames:
      - portfolio-app
  selector:
    matchLabels:
      app: portfolio-service
  endpoints:
  - port: metrics
    path: /metrics
