apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: portfolio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: microservices-demo-auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: portfolio_db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
