# postgres-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # 'postgres' in base64
  POSTGRES_USER: cG9zdGdyZXM=      # 'postgres' in base64
  JWT_SECRET: eW91ci1zZWNyZXQta2V5LWhlcmU=  # 'your-secret-key-here' in base64

